routes/web.php
<?php


use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    auth()->logout();
    return view('welcome');
});
Route::get('home', function () {
    if (auth()->user()->is_admin)
        return redirect()->route('admin.home');
    if (auth()->user()->shop) {
        if (auth()->user()->shop->status)
            return redirect()->route('seller.home');
        else {
            session()->push('message', __('msg.for_login_to_panel_confirm_needed'));
            return redirect('/');
        }
    }else{
        return redirect('/');
    }
})->name('home');

Auth::routes();

Route::group(['namespace' => 'Seller', 'prefix' => 'seller-panel', 'middleware' => ['user_type:seller', 'auth'], 'as' => 'seller.'], function () {

    Route::get('home', function () {
        return view('seller-panel.dashboard');
    })->name('home');

    Route::resource('products','ProductController');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin-panel', 'middleware' => ['user_type:admin', 'auth'], 'as' => 'admin.'], function () {

    Route::get('home', function () {
        return view('admin-panel.dashboard');
    })->name('home');

    Route::resource('sellers','SellerController')->only(['index','edit','update']);
    Route::resource('product-categories','ProductCategoryController');
    Route::resource('products','ProductController')->only(['index' , 'destroy']);
    Route::post('products/confirm/{id}','ProductController@confirmProduct')->name('products.confirm');

});

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\Sluggable;


class ProductCategory extends Model
{
    use SoftDeletes , Sluggable;

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    protected $fillable = ['name', 'status', 'creator_id'];

    protected static function boot() {
        parent::boot();
        static::deleting(function($product) {
            $product->products()->delete();
        });
    }

    public function products(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Product::class, 'product_category_id');
    }
}

app/Http/Controllers/Admin/ProductCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ProductCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $productCategories = ProductCategory::orderBy('id', 'DESC');

        if ($request->ajax()) {
            return datatables()->of($productCategories)
                ->addColumn('name', function ($row) {
                    return $row->name;
                })
                ->addColumn('slug', function ($row) {
                    return $row->slug;
                })
                ->addColumn('actions', function ($row) {
                    $buttons = '';

                        $buttons .= '<a href="' . route('admin.product-categories.edit', $row->id) . '" class="btn"><i class="fa fa-edit"></i></a>';
                        $buttons .= '<a id="' . $row->id . '" class="btn" onclick="delete_row(' . $row->id . ')"><i class="fa fa-trash"></i></a>';
                    return $buttons;

                })
                ->addColumns(['DT_RowIndex'])
                ->rawColumns(['name', 'slug', 'actions'])
                ->addIndexColumn()
                ->filterColumn('name', function ($query, $keyword) {
                    $query->where('name', 'like', "%" . $keyword . "%");
                })

                ->make(true);
        } else {
            return view('admin-panel.productCategories.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-panel.productCategories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:1|max:60',
            'status' => 'required|numeric|digits:1'
        ]);
        $productCategory = new ProductCategory();
        $productCategory->status = $request->status;
        $productCategory->name = $request->name;
        $productCategory->save();
        return redirect()->route('admin.product-categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Http\Response
     */
    public function show(ProductCategory $productCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(ProductCategory $productCategory)
    {
        return view('admin-panel.productCategories.edit', compact('productCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProductCategory  $productCategory
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, ProductCategory $productCategory)
    {
        $this->validate($request, [
            'name' => 'required|string|min:1|max:60',
            'status' => 'required|numeric|digits:1'
        ]);
        $productCategory->status = $request->status;
        $productCategory->name = $request->name;
        $productCategory->save();

        return redirect()->route('admin.product-categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProductCategory  $productCategory
     * @return array|void
     */
    public function destroy(ProductCategory $productCategory , Request $request)
    {
        if ($request->ajax()) {
            $productCategory->delete();
            return ['status' => __('msg.done_successful')];
        }else{
            return abort(404);
        }
    }
}

resources/views/admin-panel/productCategories/create.blade.php
@extends('layouts.panel.menu')

@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.product_category_create')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-roles"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.product_category')}}</li>
        </ol>
        @if($errors->any())
            <br><br>
            <ul>
                @foreach($errors->all() as $e)
                    <li class="alert-danger ">{{$e}}</li>
                @endforeach
            </ul>
        @endif
    </section>
@endsection
@section('content')
    <div class="box box-warning">

        <!-- /.box-header -->
        <div class="box-body">

            <!-- text input -->


            <form role="form" method="post" action="{{route('admin.product-categories.store')}}">
                @csrf

                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">

                        <div class="form-group col-md-6 mx-2">
                            <label for="name">{{__('msg.title')}} </label>
                            <input class="form-control" name="name" placeholder="{{__('msg.title')}}"
                                   value="{{old('name')}}"/>
                        </div><!-- /.form-group -->
<br>
                        <div class="form-group col-md-6 mx-2">
                            <label> {{__('msg.status')}} :
                                {{__('msg.active')}} <input type="radio" name="status" class="flat-red" checked
                                                              value="1">
                            </label>
                            <label>
                                {{__('msg.inactive')}} <input type="radio" name="status" class="flat-red" value="0">
                            </label>
                        </div>

                    </div>
                </div>



                <div class="input-group-btn">
                    <input type="submit" value="{{__('msg.submit')}}" class="btn btn-success" style="float: left">
                    <a href="{{route('admin.product-categories.index')}}" class="btn btn-danger"
                       style="float: left">{{__('msg.cancel')}}</a>
                </div>


            </form>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

resources/views/admin-panel/productCategories/edit.blade.php
@extends('layouts.panel.menu')
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.product_category_edit')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-roles"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.product_category')}}</li>
        </ol>
        @if($errors->any())
            <br><br>
            <ul>
                @foreach($errors->all() as $e)
                    <li class="alert-danger ">{{$e}}</li>
                @endforeach
            </ul>
        @endif
    </section>
@endsection
@section('content')
    <div class="box box-warning">

        <!-- /.box-header -->
        <div class="box-body">

            <!-- text input -->


            <form role="form" method="post"
                  action="{{route('admin.product-categories.update',['product_category'=>$productCategory->id])}}">
                @csrf
                {{method_field('PUT')}}
                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">

                        <div class="form-group col-md-6 mx-2">
                            <label for="name">{{__('msg.title')}} </label>
                            <input class="form-control" name="name" placeholder="{{__('msg.title')}}"
                                   value="{{$productCategory->name}}"/>
                        </div><!-- /.form-group -->
                        <br>
                        <div class="form-group col-md-6 mx-2">
                            <label> {{__('msg.status')}} :
                                {{__('msg.active')}} <input type="radio" name="status" class="flat-red"
                                                              @if($productCategory->status) checked @endif value="1">
                            </label>
                            <label>
                                {{__('msg.inactive')}} <input type="radio" @if(!$productCategory->status) checked
                                                                @endif name="status" class="flat-red" value="0">
                            </label>
                        </div>

                    </div>
                </div>



                <div class="input-group-btn">
                    <input type="submit" value="{{__('msg.submit')}}" class="btn btn-success" style="float: left">
                    <a href="{{route('admin.product-categories.index')}}" class="btn btn-danger"
                       style="float: left">{{__('msg.cancel')}}</a>
                </div>


            </form>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

resources/views/admin-panel/productCategories/index.blade.php
@extends('layouts.panel.menu')
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.product_categories_table')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-roles"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.product_category')}}</li>
        </ol>
    </section>
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                        <a class="btn btn-info" href="{{route('admin.product-categories.create')}}">{{__('msg.create')}}</a>
                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="table_id" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>{{__('msg.row')}}</th>
                            <th>{{__('msg.category_name')}}</th>
                            <th>{{__('msg.slug')}}</th>
                            <th>{{__('msg.actions')}}</th>

                        </tr>
                        </thead>


                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="/admin-panel/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/admin-panel/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(window).on('load', function () {
            var Selector = {
                datatable: '#table_id',
                tableBody: '#table_id tbody',
                datatableLength: '#table_id_length',
                dtPagination: '.dataTables_paginate',
                dtPaginateButton: '.paginate_button',
                dtIdFilter: '#table_id_filter',

            }
            var State = {$isClickedOnPopoverButton: true}

            $(Selector.datatable + ' thead tr').clone(true).appendTo(Selector.datatable + ' thead');
            $(Selector.datatable + ' thead tr:eq(1) th').empty();
            var $table = $(Selector.datatable).DataTable({
                paging: true,
                searching: true,
                ordering: false,
                stateSave: true,
                serverSide: true,
                processing: true,
                orderCellsTop: true,
                ajax: {
                    url: '{{route('admin.product-categories.index')}}',
                    type: 'get',
                },
                columns: [
                    {
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'name',
                        name: 'name',
                        class: 'text-center',
                        sortable: false,
                        searchable: true
                    },
                    {
                        data: 'slug',
                        name: 'slug',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'actions',
                        name: 'actions',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },

                ],
                pageLength: 10,
                lengthMenu: [
                    [5, 10, 25, 50, -1], // https://datatables.net/extensions/buttons/examples/initialisation/pageLength.html
                    [' 5', '10', '25', '50', '']
                ],
                initComplete: function () {
                    this.api().columns().every(function (index) {
                        var $column = this;
                        var numberOfColumn = $column.selector.cols;
                        var isSearchable = this.context[0].aoColumns[numberOfColumn].bSearchable;
                        if (isSearchable) {
                            var input = document.createElement("input");
                            $(input).addClass('form-control');
                            $(input).appendTo($(Selector.datatable + ' thead tr:eq(1) th:eq(' + numberOfColumn + ')').empty())
                                .on('input', function () {
                                    $column.search($(this).val(), true, false, true).draw();
                                });

                        } // if(isSearchable)
                    });
                },
                // dom: 'Bfrtip',
                dom: '<"top"Blp>rti<"clear">',
            }); // var table
            $('<div class="dataTable_wrapper-style bg-white"></div>')
                .append($(Selector.datatable))
                .insertAfter($(Selector.datatable + '_wrapper div.dataTables_processing'));

            $('<div class="dataTable_footer-style d-flex flex-column justify-content-center align-items-center px-2 py-3 bg-white"></div>')
                .append($(Selector.dtPagination).addClass('p-0 mb-2'))
                .append($(Selector.dtInfo).addClass('p-0'))
                .insertAfter($(Selector.datatable + '_wrapper .dataTable_wrapper-style'));

        });


        function delete_row(id) {
            event.preventDefault();
            var $data = {
                _token: '{{csrf_token()}}',
            };
            $.ajax({
                type: "DELETE",
                url: window.location.href+'/' + id,
                data: $data,
                success: function (res) {
                    $('#table_id').DataTable().ajax.reload();
                    // window.location.reload();
                    },
                error: function (e) {

                }
            });
        }

    </script>
@endsection