routes/web.php
<?php


use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    auth()->logout();
    return view('welcome');
});
Route::get('home', function () {
    if (auth()->user()->is_admin)
        return redirect()->route('admin.home');
    if (auth()->user()->shop) {
        if (auth()->user()->shop->status)
            return redirect()->route('seller.home');
        else {
            session()->push('message', __('msg.for_login_to_panel_confirm_needed'));
            return redirect('/');
        }
    }else{
        return redirect('/');
    }
})->name('home');

Auth::routes();

Route::group(['namespace' => 'Seller', 'prefix' => 'seller-panel', 'middleware' => ['user_type:seller', 'auth'], 'as' => 'seller.'], function () {

    Route::get('home', function () {
        return view('seller-panel.dashboard');
    })->name('home');

    Route::resource('products','ProductController');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin-panel', 'middleware' => ['user_type:admin', 'auth'], 'as' => 'admin.'], function () {

    Route::get('home', function () {
        return view('admin-panel.dashboard');
    })->name('home');

    Route::resource('sellers','SellerController')->only(['index','edit','update']);
    Route::resource('product-categories','ProductCategoryController');
    Route::resource('products','ProductController')->only(['index' , 'destroy']);
    Route::post('products/confirm/{id}','ProductController@confirmProduct')->name('products.confirm');

});

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/SellerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class SellerController extends Controller
{
    public function index(Request $request){
        $sellers = User::whereHas('shop')->orderBy('id', 'DESC');
        if ($request->ajax()) {
            return datatables()->of($sellers)
                ->addColumn('name', function ($row) {
                    return $row->fullName();
                })
                ->addColumn('shop_name', function ($row) {
                    return $row->shop ? $row->shop->name : '-';
                })

                ->addColumn('shop_status', function ($row) {
                    $status =$row->shop->status;
                    return $status ? '<span  class="btn btn-success">' . __('msg.active') . '</span>' : '<span  class="btn btn-danger">' . __('msg.inactive') . '</span>';
                })
                ->addColumn('actions', function ($row) {
                    $buttons = '';
                        $buttons .= '<a href="' . route('admin.sellers.edit', $row->id) . '" class="btn"><i class="fa fa-edit"></i></a>';
//                        $buttons .= '<a id="' . $row->id . '" class="btn" onclick="delete_row(' . $row->id . ')"><i class="fa fa-trash"></i></a>';
//                        $buttons .= '<a href="' . route('sellers.shop', $row->id) . '" class="btn"><i class="fa fa-shopping-basket"></i></a>';

                    return $buttons;

                })
                ->addColumns(['DT_RowIndex'])
                ->rawColumns(['name', 'shop_name', 'shop_status', 'actions'])
                ->addIndexColumn()
                ->make(true);
        } else {
            return view('admin-panel.sellers.index');
        }
    }

    public function edit(User $seller){
        $this->checkBeSeller($seller);
        return view('admin-panel.sellers.edit', compact( 'seller'));
    }

    public function update(User $seller , Request $request){
        $this->checkBeSeller($seller);
        $this->validate($request, [
            'status' => 'required|numeric|digits:1',
        ]);
        $seller->shop->status = $request->status;
        $seller->shop->save();
        return redirect()->route('admin.sellers.index');
    }



    private function checkBeSeller(User $user){
        if (!$user->shop)
            return abort(404);
    }
}

app/Http/Controllers/Seller/ProductController.php
<?php

namespace App\Http\Controllers\Seller;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUpdateProductRequest;
use App\Models\Product;
use App\Models\ProductCategory;
use App\repositories\IProductRepository;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public $product;

    public function __construct(IProductRepository $product)
    {
        $this->product = $product;
    }

    public function index(Request $request)
    {
        $products = $this->product->getAll();
        if ($request->ajax()) {
            return datatables()->of($products)
                ->addColumn('name', function ($row) {
                    return $row->name;
                })
                ->addColumn('category', function ($row) {
                    return $row->productCategory->name;
                })
                ->addColumn('confirm', function ($row) {
                    $confirm = $row->confirm;
                    return $confirm ? '<span  class="btn btn-success">' . __('msg.Accepted') . '</span>' : '<span  class="btn btn-warning">' . __('msg.awaiting_approval') . '</span>';
                })
                ->addColumn('status', function ($row) {
                    $status = $row->status;
                    return $status ? '<span  class="btn btn-success">' . __('msg.active') . '</span>' : '<span  class="btn btn-danger">' . __('msg.inactive') . '</span>';
                })
                ->addColumn('actions', function ($row) {
                    $buttons = '';
                    $buttons .= '<a href="' . route('seller.products.edit', $row->id) . '" class="btn"><i class="fa fa-edit"></i></a>';
                    $buttons .= '<a id="' . $row->id . '" class="btn" onclick="delete_row(' . $row->id . ')"><i class="fa fa-trash"></i></a>';

                    return $buttons;

                })
                ->addColumns(['DT_RowIndex'])
                ->rawColumns(['name', 'category', 'confirm', 'status', 'actions'])
                ->filterColumn('name', function ($query, $keyword) {
                    $query->where('name', 'like', "%" . $keyword . "%");
                })
                ->addIndexColumn()
                ->make(true);
        } else
            return view('seller-panel.products.index');
    }

    public function create()
    {
        $productCategories = $this->product->getProductCategories();
        return view('seller-panel.products.create', compact('productCategories'));
    }

    public function store(StoreUpdateProductRequest $request)
    {
        $image = $request->file('image') ? $this->uploader($request->file('image'), 'products') : '/images/statics/product-default.png';
        $collection = $request->except(['_token', '_method']);
        $collection['image'] = $image;
        $this->product->create($collection);
        return redirect()->route('seller.products.index');
    }

    public function edit(Product $product)
    {
        $this->checkBeOwnProduct($product);
        $productCategories = $this->product->getProductCategories();
        return view('seller-panel.products.edit', compact('productCategories', 'product'));
    }

    public function update(StoreUpdateProductRequest $request, Product $product)
    {
        $this->checkBeOwnProduct($product);
        $collection = $request->except(['_token', '_method']);
        $collection['image'] = $this->updateImage($product, $request->file('image'));
        $this->product->update($product, $collection);
        return redirect()->route('seller.products.index');
    }

    public function destroy(Product $product, Request $request)
    {
        $this->checkBeOwnProduct($product);
        $this->product->delete($product);
    }

    private function checkBeOwnProduct(Product $product)
    {
        if ($product->creator_id != auth()->user()->id)
            return abort(401);
    }


    //in update method if a new image upload we remove first image if this was not default
    private function updateImage($product, $file = null)
    {
        if ($file) {
            if ($product->image != '/images/statics/product-default.png') {
                try {
                    unlink(public_path($product->image));
                } catch (\Exception $e) {
                }
            }
            return $this->uploader($file, 'products');
        }
        return $product->image;
    }
}

resources/views/admin-panel/sellers/edit.blade.php
@extends('layouts.panel.menu')
@section('css')
@endsection
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.see_and_confirm')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-sellers"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.sellers')}}</li>
        </ol>
        @if($errors->any())
            <br><br>
            <ul>
                @foreach($errors->all() as $e)
                    <li class="alert-danger ">{{$e}}</li>
                @endforeach
            </ul>
        @endif
    </section>
@endsection
@section('content')
    <div class="box box-warning">

        <!-- /.box-header -->
        <div class="box-body">

            <!-- text input -->


            <form role="form" method="post" action="{{route('admin.sellers.update',['seller'=>$seller->id])}}"
                  enctype="multipart/form-data">
                @csrf
                {{method_field('PUT')}}
                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">

                        <div class="form-group col-md-6 mx-2">
                            <label for="fname">{{__('msg.fname')}} </label>
                            <input class="form-control"  readonly placeholder="{{__('msg.fname')}}"
                                   value="{{$seller->fname}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="lname">{{__('msg.lname')}} </label>
                            <input class="form-control"  readonly placeholder="{{__('msg.lname')}}"
                                   value="{{$seller->lname}}"/>
                        </div><!-- /.form-group -->


                        <div class="form-group col-md-6 mx-2">
                            <label for="email">{{__('msg.email')}} </label>
                            <input class="form-control" type="email" readonly placeholder="{{__('msg.email')}}"
                                   value="{{$seller->email}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="mobile">{{__('msg.mobile')}} </label>
                            <input class="form-control" readonly placeholder="{{__('msg.mobile')}}"
                                   value="{{$seller->shop->mobile}}"/>
                        </div><!-- /.form-group -->


                        <div class="form-group col-md-6 mx-2">
                            <label for="national_code">{{__('msg.national_code')}} </label>
                            <input class="form-control" readonly
                                   placeholder="{{__('msg.national_code')}}" value="{{$seller->shop->national_code}}"/>
                        </div><!-- /.form-group -->


                        <div class="form-group col-md-6 mx-2">
                            <label for="address">{{__('msg.address')}} </label>
                            <input class="form-control" readonly placeholder="{{__('msg.address')}}"
                                   value="{{$seller->shop->address}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="postal_code">{{__('msg.postal_code')}} </label>
                            <input class="form-control" readonly placeholder="{{__('msg.postal_code')}}"
                                   value="{{$seller->shop->postal_code}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="shaba_code">{{__('msg.shaba_code')}} </label>
                            <input class="form-control" readonly placeholder="{{__('msg.shaba_code')}}"
                                   value="{{$seller->shop->shaba_code}}"/>
                        </div><!-- /.form-group -->


                        <div class="form-group col-md-6 mx-2">
                            <label for="shop_name">{{__('msg.shop_name')}} </label>
                            <input class="form-control"  readonly placeholder="{{__('msg.shop_name')}}"
                                   value="{{$seller->shop->shop_name}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label> {{__('msg.shop_status')}} :
                                {{__('msg.active')}} <input type="radio" name="status" class="flat-red"
                                                              @if($seller->shop->status) checked @endif value="1">
                            </label>
                            <label>
                                {{__('msg.inactive')}} <input type="radio" @if(!$seller->shop->status) checked
                                                                @endif name="status" class="flat-red" value="0">
                            </label>
                        </div>



                    </div>

                </div>
                <br><br><br><br>
                <div class="input-group-btn">
                    <input type="submit" value="{{__('msg.submit')}}" class="btn btn-success" style="float: left">
                    <a href="{{route('admin.sellers.index')}}" class="btn btn-danger"
                       style="float: left">{{__('msg.cancel')}}</a>
                </div>


            </form>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

resources/views/admin-panel/sellers/index.blade.php
@extends('layouts.panel.menu')
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.sellers_table')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{route('home')}}"><i class="fa fa-admins"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.sellers')}}</li>
        </ol>
    </section>
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">

                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="table_id" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>{{__('msg.row')}}</th>
                            <th>{{__('msg.full_name')}}</th>
                            <th>{{__('msg.shop_name')}}</th>
                            <th>{{__('msg.shop_status')}}</th>
                            <th>{{__('msg.actions')}}</th>

                        </tr>
                        </thead>


                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="/admin-panel/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/admin-panel/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(window).on('load', function () {
            var Selector = {
                datatable: '#table_id',
                tableBody: '#table_id tbody',
                datatableLength: '#table_id_length',
                dtPagination: '.dataTables_paginate',
                dtPaginateButton: '.paginate_button',
                dtIdFilter: '#table_id_filter',

            }
            var State = {$isClickedOnPopoverButton: true}

            $(Selector.datatable + ' thead tr').clone(true).appendTo(Selector.datatable + ' thead');
            $(Selector.datatable + ' thead tr:eq(1) th').empty();
            var $table = $(Selector.datatable).DataTable({
                paging: true,
                searching: false,
                ordering: false,
                stateSave: true,
                serverSide: true,
                processing: true,
                orderCellsTop: true,
                ajax: {
                    url: '{{route('admin.sellers.index')}}',
                    type: 'get',
                },
                columns: [
                    {
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'name',
                        name: 'name',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'shop_name',
                        name: 'shop_name',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'shop_status',
                        name: 'shop_status',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'actions',
                        name: 'actions',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },

                ],
                pageLength: 10,
                lengthMenu: [
                    [5, 10, 25, 50, -1], // https://datatables.net/extensions/buttons/examples/initialisation/pageLength.html
                    [' 5', '10', '25', '50', '']
                ],

                // dom: 'Bfrtip',
                dom: '<"top"Blp>rti<"clear">',
            }); // var table
            $('<div class="dataTable_wrapper-style bg-white"></div>')
                .append($(Selector.datatable))
                .insertAfter($(Selector.datatable + '_wrapper div.dataTables_processing'));

            $('<div class="dataTable_footer-style d-flex flex-column justify-content-center align-items-center px-2 py-3 bg-white"></div>')
                .append($(Selector.dtPagination).addClass('p-0 mb-2'))
                .append($(Selector.dtInfo).addClass('p-0'))
                .insertAfter($(Selector.datatable + '_wrapper .dataTable_wrapper-style'));

        });



    </script>
@endsection