routes/web.php
<?php


use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    auth()->logout();
    return view('welcome');
});
Route::get('home', function () {
    if (auth()->user()->is_admin)
        return redirect()->route('admin.home');
    if (auth()->user()->shop) {
        if (auth()->user()->shop->status)
            return redirect()->route('seller.home');
        else {
            session()->push('message', __('msg.for_login_to_panel_confirm_needed'));
            return redirect('/');
        }
    }else{
        return redirect('/');
    }
})->name('home');

Auth::routes();

Route::group(['namespace' => 'Seller', 'prefix' => 'seller-panel', 'middleware' => ['user_type:seller', 'auth'], 'as' => 'seller.'], function () {

    Route::get('home', function () {
        return view('seller-panel.dashboard');
    })->name('home');

    Route::resource('products','ProductController');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin-panel', 'middleware' => ['user_type:admin', 'auth'], 'as' => 'admin.'], function () {

    Route::get('home', function () {
        return view('admin-panel.dashboard');
    })->name('home');

    Route::resource('sellers','SellerController')->only(['index','edit','update']);
    Route::resource('product-categories','ProductCategoryController');
    Route::resource('products','ProductController')->only(['index' , 'destroy']);
    Route::post('products/confirm/{id}','ProductController@confirmProduct')->name('products.confirm');

});

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use App\Events\ProductChangeEvent;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use PHPUnit\Exception;

class Product extends Model
{
    use SoftDeletes , Sluggable;
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
    protected static function boot() {
        parent::boot();
        static::deleting(function($product) {

                if ($product->image != '/images/statics/product-default.png') {
                    try {
                        unlink(public_path($product->image));
                    } catch (Exception $e) {

                    }
                }
        });
    }
    protected $dispatchesEvents = [
        'created'=>ProductChangeEvent::class,
        'updated'=>ProductChangeEvent::class,
        'deleted'=>ProductChangeEvent::class,
    ];
    protected $guarded=[];

    public function productCategory(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(ProductCategory::class , 'product_category_id');
    }

    public function creator(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class , 'creator_id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use PHPUnit\Exception;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     * @throws \Exception
     */
    public function index(Request $request)
    {
        $products = Product::orderBy('id', 'desc');
        if ($request->ajax()) {
            return datatables()->of($products)
                ->addColumn('name', function ($row) {
                    return $row->name;
                })
                ->addColumn('category', function ($row) {
                    return $row->productCategory->name;
                })
                ->addColumn('confirm', function ($row) {
                    $confirm = $row->confirm;
                    return $confirm ? '<span  class="btn btn-success">' . __('msg.Accepted') . '</span>' : '<span  class="btn btn-warning">' . __('msg.awaiting_approval') . '</span>';
                })
                ->addColumn('status', function ($row) {
                    $status = $row->status;
                    return $status ? '<span  class="btn btn-success">' . __('msg.active') . '</span>' : '<span  class="btn btn-danger">' . __('msg.inactive') . '</span>';
                })
                ->addColumn('actions', function ($row) {
                    $buttons = '';
                    $buttons .= '<a id="' . $row->id . '" class="btn" onclick="delete_row(' . $row->id . ')"><i class="fa fa-trash"></i></a>';
                    if (!$row->confirm)
                        $buttons .= '<a id="' . $row->id . '" class="btn" onclick="confirm(' . $row->id . ')"><i class="fa fa-check"></i></a>';
                    return $buttons;

                })
                ->addColumns(['DT_RowIndex'])
                ->rawColumns(['name', 'category', 'confirm', 'status', 'actions'])
                ->filterColumn('name', function ($query, $keyword) {
                    $query->where('name', 'like', "%" . $keyword . "%");
                })
                ->addIndexColumn()
                ->make(true);
        } else {
            return view('admin-panel.products.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Product $product
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product, Request $request)
    {
            $product->delete();
    }

    public function confirmProduct($id){
        $product = Product::findOrFail($id);
        $product->confirm = true;
        $product->save();
    }
}

app/Http/Controllers/Seller/ProductController.php
<?php

namespace App\Http\Controllers\Seller;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUpdateProductRequest;
use App\Models\Product;
use App\Models\ProductCategory;
use App\repositories\IProductRepository;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public $product;

    public function __construct(IProductRepository $product)
    {
        $this->product = $product;
    }

    public function index(Request $request)
    {
        $products = $this->product->getAll();
        if ($request->ajax()) {
            return datatables()->of($products)
                ->addColumn('name', function ($row) {
                    return $row->name;
                })
                ->addColumn('category', function ($row) {
                    return $row->productCategory->name;
                })
                ->addColumn('confirm', function ($row) {
                    $confirm = $row->confirm;
                    return $confirm ? '<span  class="btn btn-success">' . __('msg.Accepted') . '</span>' : '<span  class="btn btn-warning">' . __('msg.awaiting_approval') . '</span>';
                })
                ->addColumn('status', function ($row) {
                    $status = $row->status;
                    return $status ? '<span  class="btn btn-success">' . __('msg.active') . '</span>' : '<span  class="btn btn-danger">' . __('msg.inactive') . '</span>';
                })
                ->addColumn('actions', function ($row) {
                    $buttons = '';
                    $buttons .= '<a href="' . route('seller.products.edit', $row->id) . '" class="btn"><i class="fa fa-edit"></i></a>';
                    $buttons .= '<a id="' . $row->id . '" class="btn" onclick="delete_row(' . $row->id . ')"><i class="fa fa-trash"></i></a>';

                    return $buttons;

                })
                ->addColumns(['DT_RowIndex'])
                ->rawColumns(['name', 'category', 'confirm', 'status', 'actions'])
                ->filterColumn('name', function ($query, $keyword) {
                    $query->where('name', 'like', "%" . $keyword . "%");
                })
                ->addIndexColumn()
                ->make(true);
        } else
            return view('seller-panel.products.index');
    }

    public function create()
    {
        $productCategories = $this->product->getProductCategories();
        return view('seller-panel.products.create', compact('productCategories'));
    }

    public function store(StoreUpdateProductRequest $request)
    {
        $image = $request->file('image') ? $this->uploader($request->file('image'), 'products') : '/images/statics/product-default.png';
        $collection = $request->except(['_token', '_method']);
        $collection['image'] = $image;
        $this->product->create($collection);
        return redirect()->route('seller.products.index');
    }

    public function edit(Product $product)
    {
        $this->checkBeOwnProduct($product);
        $productCategories = $this->product->getProductCategories();
        return view('seller-panel.products.edit', compact('productCategories', 'product'));
    }

    public function update(StoreUpdateProductRequest $request, Product $product)
    {
        $this->checkBeOwnProduct($product);
        $collection = $request->except(['_token', '_method']);
        $collection['image'] = $this->updateImage($product, $request->file('image'));
        $this->product->update($product, $collection);
        return redirect()->route('seller.products.index');
    }

    public function destroy(Product $product, Request $request)
    {
        $this->checkBeOwnProduct($product);
        $this->product->delete($product);
    }

    private function checkBeOwnProduct(Product $product)
    {
        if ($product->creator_id != auth()->user()->id)
            return abort(401);
    }


    //in update method if a new image upload we remove first image if this was not default
    private function updateImage($product, $file = null)
    {
        if ($file) {
            if ($product->image != '/images/statics/product-default.png') {
                try {
                    unlink(public_path($product->image));
                } catch (\Exception $e) {
                }
            }
            return $this->uploader($file, 'products');
        }
        return $product->image;
    }
}

resources/views/seller-panel/products/create.blade.php
@extends('layouts.panel.menu')
@section('css')
    <link rel="stylesheet" href="/admin-panel/bower_components/select2/dist/css/select2.min.css">
@endsection
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.product_create')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-roles"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.products')}}</li>
        </ol>
        @if($errors->any())
            <br><br>
            <ul>
                @foreach($errors->all() as $e)
                    <li class="alert-danger ">{{$e}}</li>
                @endforeach
            </ul>
        @endif
    </section>
@endsection
@section('content')
    <div class="box box-warning">

        <!-- /.box-header -->
        <div class="box-body">

            <!-- text input -->


            <form role="form" method="post" action="{{route('seller.products.store')}}" enctype="multipart/form-data">
                @csrf

                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">

                        <div class="form-group col-md-6 mx-2">
                            <label for="name">{{__('msg.title')}} </label>
                            <input class="form-control" name="name" placeholder="{{__('msg.title')}}"
                                   required value="{{old('name')}}"/>
                        </div><!-- /.form-group -->


                        <div class="form-group col-md-6 mx-2">
                            <label for="price">{{__('msg.main_price') . ' (' . __('msg.currency') . ') '}} </label>
                            <input class="form-control" type="number" name="price" required
                                   placeholder="{{__('msg.main_price')}}"
                                   value="{{old('price')}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="discount">{{__('msg.discount')}} </label>
                            <input class="form-control" name="discount" type="number"
                                   placeholder="{{__('msg.discount')}}"
                                   value="{{old('discount')}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="count">{{__('msg.count')}} </label>
                            <input class="form-control" required name="count" type="number" placeholder="{{__('msg.count')}}"
                                   value="{{old('count')}}"/>
                        </div><!-- /.form-group -->

                    </div>
                </div>
                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">


                        <div class="form-group col-md-6 mx-2">
                            <label> {{__('msg.status')}} :
                                {{__('msg.active')}} <input type="radio" name="status" class="flat-red" checked
                                                              value="1">
                            </label>
                            <label>
                                {{__('msg.inactive')}} <input type="radio" name="status" class="flat-red" value="0">
                            </label>
                        </div>


                        <div class="form-group col-md-6 mx-2">
                            <label for="name">{{__('msg.description')}} </label>
                            <textarea id="mytextarea"  name="description"> {{old('description')}} </textarea>
                        </div>

                    </div>
                </div>


                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">


                        <div class="form-group col-md-6 mx-2">
                            <label>{{__('msg.product_category')}}</label>
                            <select class="form-control" name="category" required>
                                @foreach($productCategories as $productCategory)
                                    <option value="{{$productCategory->id}}">{{$productCategory->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group col-md-6 mx-2">
                            <label for="avatar">{{__('msg.image')}} </label>
                            <input class="form-control" accept=".jpg,.jpeg,.png,.bmp" type="file" name="image"/>
                        </div><!-- /.form-group -->



                    </div>
                </div>




                <div class="input-group-btn">
                    <input type="submit" value="{{__('msg.submit')}}" class="btn btn-success" style="float: left">
                    <a href="{{route('seller.products.index')}}" class="btn btn-danger"
                       style="float: left">{{__('msg.cancel')}}</a>
                </div>


            </form>

        </div>
        <!-- /.box-body -->
    </div>

@endsection
@section('script')
    <script src="/admin-panel/bower_components/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea#mytextarea',
            plugins: 'advlist autolink link lists preview table code pagebreak',
            menubar: false,
            language: 'fa',
            height: 300,
            relative_urls: false,
            toolbar: 'undo redo | removeformat preview code | fontsizeselect bullist numlist | alignleft aligncenter alignright alignjustify | bold italic | pagebreak table link',
        });

    </script>




@endsection

resources/views/seller-panel/products/edit.blade.php
@extends('layouts.panel.menu')
@section('css')
    <link rel="stylesheet" href="/admin-panel/bower_components/select2/dist/css/select2.min.css">
@endsection
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.product_edit')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-roles"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.products')}}</li>
        </ol>
        @if($errors->any())
            <br><br>
            <ul>
                @foreach($errors->all() as $e)
                    <li class="alert-danger ">{{$e}}</li>
                @endforeach
            </ul>
        @endif
    </section>
@endsection
@section('content')
    <div class="box box-warning">

        <!-- /.box-header -->
        <div class="box-body">

            <!-- text input -->


            <form role="form" method="post" action="{{route('seller.products.update',['product'=>$product->id])}}"
                  enctype="multipart/form-data">
                @csrf
                {{method_field('PUT')}}
                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">

                        <div class="form-group col-md-6 mx-2">
                            <label for="name">{{__('msg.title')}} </label>
                            <input class="form-control" name="name" placeholder="{{__('msg.title')}}"
                                   required value="{{$product->name}}"/>
                        </div><!-- /.form-group -->


                        <div class="form-group col-md-6 mx-2">
                            <label for="price">{{__('msg.main_price') . ' (' . __('msg.currency') . ') '}} </label>
                            <input class="form-control" type="number" name="price" required
                                   placeholder="{{__('msg.main_price')}}"
                                   value="{{$product->price}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="discount">{{__('msg.discount')}} </label>
                            <input class="form-control" name="discount" type="number"
                                   placeholder="{{__('msg.discount')}}"
                                   value="{{$product->discount}}"/>
                        </div><!-- /.form-group -->

                        <div class="form-group col-md-6 mx-2">
                            <label for="count">{{__('msg.count')}} </label>
                            <input class="form-control" required name="count" type="number"
                                   placeholder="{{__('msg.count')}}"
                                   value="{{$product->count}}"/>
                        </div><!-- /.form-group -->

                    </div>
                </div>
                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">


                        <div class="form-group col-md-6 mx-2">
                            <label> {{__('msg.status')}} :
                                {{__('msg.active')}} <input type="radio" name="status" class="flat-red"
                                                            @if($product->status) checked @endif
                                                            value="1">
                            </label>
                            <label>
                                {{__('msg.inactive')}} <input type="radio" name="status" class="flat-red"
                                                              @if(!$product->status) checked @endif value="0">
                            </label>
                        </div>


                        <div class="form-group col-md-6 mx-2">
                            <label for="name">{{__('msg.description')}} </label>
                            <textarea id="mytextarea" name="description"> {{$product->description}} </textarea>
                        </div>

                    </div>
                </div>


                <div class="row align-items-end col-12">
                    <div class="card-body d-flex flex-column flex-md-row align-items-md-end p-2">


                        <div class="form-group col-md-6 mx-2">
                            <label>{{__('msg.product_category')}}</label>
                            <select class="form-control" name="category" required>
                                @foreach($productCategories as $productCategory)
                                    <option value="{{$productCategory->id}}"
                                            @if($product->product_category_id == $productCategory->id) selected @endif>
                                        {{$productCategory->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group col-md-6 mx-2">
                            <label for="avatar">{{__('msg.image')}} </label>
                            <img src="{{$product->image}}" width="100">
                            <input class="form-control" accept=".jpg,.jpeg,.png,.bmp" type="file" name="image"/>
                        </div><!-- /.form-group -->


                    </div>
                </div>


                <div class="input-group-btn">
                    <input type="submit" value="{{__('msg.submit')}}" class="btn btn-success" style="float: left">
                    <a href="{{route('seller.products.index')}}" class="btn btn-danger"
                       style="float: left">{{__('msg.cancel')}}</a>
                </div>


            </form>

        </div>
        <!-- /.box-body -->
    </div>

@endsection
@section('script')
    <script src="/admin-panel/bower_components/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea#mytextarea',
            plugins: 'advlist autolink link lists preview table code pagebreak',
            menubar: false,
            language: 'fa',
            height: 300,
            relative_urls: false,
            toolbar: 'undo redo | removeformat preview code | fontsizeselect bullist numlist | alignleft aligncenter alignright alignjustify | bold italic | pagebreak table link',
        });

    </script>




@endsection

resources/views/seller-panel/products/index.blade.php
@extends('layouts.panel.menu')
@section('header')
    <section class="content-header">
        <h1>
            {{__('msg.products_table')}}
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-roles"></i>{{__('msg.home')}}</a></li>
            <li class="active">{{__('msg.products')}}</li>
        </ol>
    </section>
    @if(session()->has('msg'))
        <div class="alert alert-success">
            {{session()->get('msg')}}
        </div>
        <br>
    @endif
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">

                        <a class="btn btn-info" href="{{route('seller.products.create')}}">{{__('msg.create')}}</a>

                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="table_id" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>{{__('msg.row')}}</th>
                            <th>{{__('msg.product_name')}}</th>
                            <th>{{__('msg.product_category')}}</th>
                            <th>{{__('msg.confirm_status')}}</th>
                            <th>{{__('msg.show_status')}}</th>
                            <th>{{__('msg.actions')}}</th>

                        </tr>
                        </thead>


                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="/admin-panel/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/admin-panel/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(window).on('load', function () {
            var Selector = {
                datatable: '#table_id',
                tableBody: '#table_id tbody',
                datatableLength: '#table_id_length',
                dtPagination: '.dataTables_paginate',
                dtPaginateButton: '.paginate_button',
                dtIdFilter: '#table_id_filter',

            }
            var State = {$isClickedOnPopoverButton: true}

            $(Selector.datatable + ' thead tr').clone(true).appendTo(Selector.datatable + ' thead');
            $(Selector.datatable + ' thead tr:eq(1) th').empty();
            var $table = $(Selector.datatable).DataTable({
                paging: true,
                searching: true,
                ordering: false,
                stateSave: true,
                serverSide: true,
                processing: true,
                orderCellsTop: true,
                ajax: {
                    url: '{{route('seller.products.index')}}',
                    type: 'get',
                },
                columns: [
                    {
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'name',
                        name: 'name',
                        class: 'text-center',
                        sortable: false,
                        searchable: true
                    },
                    {
                        data: 'category',
                        name: 'category',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'confirm',
                        name: 'confirm',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'status',
                        name: 'status',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },
                    {
                        data: 'actions',
                        name: 'actions',
                        class: 'text-center',
                        sortable: false,
                        searchable: false
                    },

                ],
                pageLength: 10,
                lengthMenu: [
                    [5, 10, 25, 50, -1], // https://datatables.net/extensions/buttons/examples/initialisation/pageLength.html
                    [' 5', '10', '25', '50', '']
                ],
                initComplete: function () {
                    this.api().columns().every(function (index) {
                        var $column = this;
                        var numberOfColumn = $column.selector.cols;
                        var isSearchable = this.context[0].aoColumns[numberOfColumn].bSearchable;
                        if (isSearchable) {
                            var input = document.createElement("input");
                            // $(input).addClass('form-control');
                            $(input).appendTo($(Selector.datatable + ' thead tr:eq(1) th:eq(' + numberOfColumn + ')').empty())
                                .on('input', function () {
                                    $column.search($(this).val(), true, false, true).draw();
                                });

                        } // if(isSearchable)
                    });
                },
                // dom: 'Bfrtip',
                dom: '<"top"Blp>rti<"clear">',
            }); // var table
            $('<div class="dataTable_wrapper-style bg-white"></div>')
                .append($(Selector.datatable))
                .insertAfter($(Selector.datatable + '_wrapper div.dataTables_processing'));

            $('<div class="dataTable_footer-style d-flex flex-column justify-content-center align-items-center px-2 py-3 bg-white"></div>')
                .append($(Selector.dtPagination).addClass('p-0 mb-2'))
                .append($(Selector.dtInfo).addClass('p-0'))
                .insertAfter($(Selector.datatable + '_wrapper .dataTable_wrapper-style'));

        });


        function delete_row(id) {
            event.preventDefault();
            var $data = {
                _token: '{{csrf_token()}}',
            };
            $.ajax({
                type: "DELETE",
                url:window.location.href+'/' + id,
                data: $data,
                success: function (res) {
                    $('#table_id').DataTable().ajax.reload();
                    // window.location.reload();
                    },
                error: function (e) {

                }
            });
        }

    </script>
@endsection